import { useCurrentFrame, interpolate, Easing } from "remotion";
import SceneWrapper from "../SceneWrapper";
import AnimatedText from "../AnimatedText";
import { SCENE_DURATIONS } from "../constants";

function ActionPlanScene({ data, colors }) {
  const frame = useCurrentFrame();
  const actions = data?.actions || [];

  const lineWidth = interpolate(frame, [15, 45], [0, 200], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.out(Easing.cubic),
  });

  return (
    <SceneWrapper durationInFrames={SCENE_DURATIONS.actionPlan}>
      <div
        style={{
          width: "100%",
          maxWidth: 700,
          fontFamily: "Inter, system-ui, sans-serif",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          textAlign: "center",
        }}
      >
        <AnimatedText
          delay={3}
          style={{
            fontSize: 14,
            fontWeight: 600,
            color: colors.chart1,
            letterSpacing: 2,
            textTransform: "uppercase",
            marginBottom: 8,
          }}
        >
          Council Consensus
        </AnimatedText>

        <AnimatedText
          delay={8}
          style={{
            fontSize: 32,
            fontWeight: 700,
            color: colors.textPrimary,
            marginBottom: 6,
          }}
        >
          Your Action Plan
        </AnimatedText>

        <div
          style={{
            width: lineWidth,
            height: 3,
            backgroundColor: colors.chart1,
            borderRadius: 2,
            margin: "12px 0 28px",
          }}
        />

        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: 12,
            width: "100%",
            maxWidth: 520,
            textAlign: "left",
          }}
        >
          {actions.slice(0, 4).map((action, i) => {
            const itemOpacity = interpolate(
              frame,
              [22 + i * 10, 32 + i * 10],
              [0, 1],
              { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
            );
            const itemX = interpolate(
              frame,
              [22 + i * 10, 32 + i * 10],
              [20, 0],
              {
                extrapolateLeft: "clamp",
                extrapolateRight: "clamp",
                easing: Easing.out(Easing.cubic),
              }
            );

            return (
              <div
                key={i}
                style={{
                  opacity: itemOpacity,
                  transform: `translateX(${itemX}px)`,
                  display: "flex",
                  alignItems: "center",
                  gap: 12,
                  padding: "10px 16px",
                  backgroundColor: colors.card,
                  border: `1px solid ${colors.cardBorder}`,
                  borderRadius: 10,
                }}
              >
                <div
                  style={{
                    width: 28,
                    height: 28,
                    borderRadius: "50%",
                    background: `linear-gradient(135deg, ${colors.primary}, ${colors.chart1})`,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    fontSize: 13,
                    fontWeight: 700,
                    color: colors.primaryForeground,
                    flexShrink: 0,
                  }}
                >
                  {i + 1}
                </div>
                <span style={{ fontSize: 15, color: colors.textPrimary }}>
                  {action}
                </span>
              </div>
            );
          })}
        </div>

        <AnimatedText
          delay={75}
          style={{
            fontSize: 13,
            color: colors.textMuted,
            marginTop: 24,
          }}
        >
          Generated by Money Council AI - All agents in agreement
        </AnimatedText>
      </div>
    </SceneWrapper>
  );
}

export default ActionPlanScene;